kubernetes-sigs/contributor-tweets

GUIDELINES.md
README.md

Updated README

---

tweets/17-08-2020-lifecycle-survey.tweet

Signed-off-by: Matthew Broberg <matt@opensource.com>

Tweet for lifecycle survey

---

tweets/08-31-2020-slack-channel-tip.tweet

Signed-off-by: Jorge O. Castro <jorgec@vmware.com>

Add a tip for using slack URLs

---

tweets/06-10-2020-election-closing.tweet

Signed-off-by: Jorge O. Castro <jorgec@vmware.com>

Add reminder for SC election deadline

---

tweets/10-09-2020-election-results.tweet

Creating a placeholder tweet for the steering committee election results. To be updated and pushed out when the announcement is made on Monday, October 12th.
/hold

Election Results Placeholder

---

tweets/18-10-2020-steering-elections.tweet

Adding steering election blog tweet

---

tweets/11-12-2020-kubecon-freepass.tweet

With KubeCon NA only 5 days away, I wanted to send out a tweet reminding contributors that they can get access to the keynotes for free.

Adding a tweet about free keynote passes for KubeConNA

---

tweets/11-25-2020-contributor-celebration.tweet

Per @mrbobbytables' request - adding a tweet to promote the upcoming 2020 Contributor Celebration.

Creating a tweet about the Contributor Celebration

---

OWNERS

Adding Pensu as owners

---

tweets/2021-02-09-slack-pronouns.tweet
tweets/2021-02-09-upcoming-removals.tweet

Adding a tweet to promote the use of pronouns in the Kubernetes slack.
I put in kubernetes.slack.com to help give people an immediate call to action. Don't know if there's a better link we could give. I didn't see a way to send people directly to their profiles.
There will be several tweet PRs today so putting a hold on this for now in order to space them out.
/hold
cc: @jberkus

Slack pronouns

---

tweets/2021-02-09-KubeConEU-scholarships.tweet

Adding in a new tweet to help promote scholarship opportunities for KubeCon EU 2021 Virtual. The deadline is in April, so probably will retweet this or add new tweets closer to the deadline as well.
Wording fixes/suggestions welcome of course.
A couple other tweets incoming today, so it's probably best to space them out. Will hold this one for now.
/hold

Promoting KubeConEU 2021 Scholarships

---

tweets/2021-06-14-contributor-meeting.tweet

Creating a tweet to advertise the upcoming monthly community meeting per @jberkus request.

Monthly Community Meeting Tweet

---

tweets/09-01-2021-sig-autoscaling
tweets/09-01-2021-sig-scheduling

This is the drafted tweet on SIG-Scheduling of the _Help Wanted_ section in [Kubernetes Community Annual Report 2020](https://www.cncf.io/reports/kubernetes-community-annual-report-2020/)
Signed-off-by: Atharva Shinde <atharvashinde179@gmail.com>
Issue: #59 
cc: @parispittman @kaslin @sftim @chris-short

Tweet on SIG-Scheduling

---

tweets/09-01-2021-sig-autoscaling

This is the drafted tweet on SIG-Autoscaling for the _Help Wanted_ section in [Kubernetes Community Annual Report 2020](https://www.cncf.io/reports/kubernetes-community-annual-report-2020/)
Signed-off-by: Atharva Shinde <atharvashinde179@gmail.com>
Issue: #59 
cc: @parispittman @kaslin @sftim @mbbroberg

Tweet on SIG Autoscaling 

---

tweets/01-12-2021-21-00Mermaid-diagrams.tweet

Announce the blog article [Improve your documentation with Mermaid.js diagrams](https://www.kubernetes.dev/blog/2021/12/01/improve-your-documentation-with-mermaid.js-diagrams/)

Add new tweet: announce “Improve your documentation with Mermaid.js diagrams”

---

README.md

Closes #197 
- Removed and updated broken links from README.md
Please feel free to suggest any edits if needed. Thanks.

docs: removed broken links from README

---

.github/workflows/main.yml

Fixes: https://github.com/kubernetes-sigs/contributor-tweets/issues/269

Upgrade twitter-together

---

.github/workflows/main.yml

This issue fixes https://github.com/kubernetes-sigs/contributor-tweets/issues/272

Fix Validate command

---

README.md

Updating to Contrib Comms

---

OWNERS

Updating owners file again again again

Updating Owners file
